services:
  - name: apex-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: BOT_TOKEN
        value: "YOUR_BOT_TOKEN_HERE"
      - key: CLIENT_ID
        value: "1485251474102550628"
      - key: GUILD_ID
        value: "1480980406118383636"
      - key: OWNER_ID
        value: "210752730539622410"
